-------------------------------------------------------------------------------
Test set: StackWithMaxTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec <<< FAILURE! - in StackWithMaxTest
stackWithMax1(StackWithMaxTest)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at StackWithMaxTest.lambda$assertTracksMax$2(StackWithMaxTest.java:51)

stackWithMax2(StackWithMaxTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at StackWithMaxTest.lambda$assertTracksMax$2(StackWithMaxTest.java:51)

